/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) C_terms_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, nnz, is_sparse, c, k;
  const casadi_int *colind, *row;
  size_t p_nrow, p_ncol;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  nnz = sp[ncol];
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  if (is_sparse) {
#ifndef CASADI_MEX_NO_SPARSE
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
#else /* CASADI_MEX_NO_SPARSE */
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Sparse inputs disabled.");
#endif /* CASADI_MEX_NO_SPARSE */
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch.");
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, nnz, c, k;
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  nnz = sp[ncol];
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* f:(i0[5],i1[5])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a5, a6, a7, a8, a9;
  a0=4.0000000000000002e-01;
  a1=arg[0]? arg[0][1] : 0;
  a2=sin(a1);
  a3=9.8100000000000005e+00;
  a4=arg[0]? arg[0][0] : 0;
  a5=sin(a4);
  a5=(a3*a5);
  a6=(a2*a5);
  a1=cos(a1);
  a4=cos(a4);
  a3=(a3*a4);
  a4=(a1*a3);
  a6=(a6-a4);
  a4=(a0*a2);
  a7=arg[1]? arg[1][0] : 0;
  a8=(a4*a7);
  a9=arg[1]? arg[1][1] : 0;
  a10=(a8*a9);
  a6=(a6-a10);
  a10=(a0*a6);
  a11=(a0*a8);
  a12=(a7+a9);
  a11=(a11*a12);
  a13=2.;
  a14=(a0*a1);
  a7=(a14*a7);
  a15=(a13*a7);
  a15=(a15*a8);
  a11=(a11-a15);
  a15=(a13*a8);
  a15=(a15*a7);
  a11=(a11+a15);
  a10=(a10+a11);
  a11=7.5000000000000000e-01;
  a15=arg[0]? arg[0][2] : 0;
  a16=cos(a15);
  a17=(a16*a6);
  a15=sin(a15);
  a9=(a7*a9);
  a1=(a1*a5);
  a2=(a2*a3);
  a1=(a1+a2);
  a9=(a9-a1);
  a1=(a15*a9);
  a17=(a17-a1);
  a1=(a0*a15);
  a2=(a1*a12);
  a5=(a16*a8);
  a2=(a2+a5);
  a5=(a15*a7);
  a2=(a2+a5);
  a5=arg[1]? arg[1][2] : 0;
  a18=(a2*a5);
  a17=(a17-a18);
  a18=(a11*a17);
  a19=(a11*a2);
  a20=(a12+a5);
  a19=(a19*a20);
  a21=5.;
  a22=(a0*a16);
  a23=(a22*a12);
  a24=(a15*a8);
  a23=(a23-a24);
  a24=(a16*a7);
  a23=(a23+a24);
  a24=(a21*a23);
  a24=(a24*a2);
  a19=(a19-a24);
  a24=(a21*a2);
  a24=(a24*a23);
  a19=(a19+a24);
  a18=(a18+a19);
  a19=arg[0]? arg[0][3] : 0;
  a24=cos(a19);
  a25=(a24*a17);
  a19=sin(a19);
  a26=(a16*a9);
  a27=(a15*a6);
  a26=(a26+a27);
  a5=(a23*a5);
  a26=(a26+a5);
  a5=(a19*a26);
  a25=(a25-a5);
  a5=(a24*a2);
  a27=(a19*a23);
  a5=(a5+a27);
  a27=arg[1]? arg[1][3] : 0;
  a28=(a5*a27);
  a25=(a25-a28);
  a28=(a0*a25);
  a29=(a0*a5);
  a30=(a20+a27);
  a29=(a29*a30);
  a31=(a24*a23);
  a32=(a19*a2);
  a31=(a31-a32);
  a32=(a13*a31);
  a32=(a32*a5);
  a29=(a29-a32);
  a32=(a13*a5);
  a32=(a32*a31);
  a29=(a29+a32);
  a28=(a28+a29);
  a29=arg[0]? arg[0][4] : 0;
  a32=cos(a29);
  a33=(a32*a25);
  a29=sin(a29);
  a34=(a24*a26);
  a35=(a19*a17);
  a34=(a34+a35);
  a27=(a31*a27);
  a34=(a34+a27);
  a27=(a29*a34);
  a33=(a33-a27);
  a27=(a0*a29);
  a35=(a27*a30);
  a36=(a32*a5);
  a35=(a35+a36);
  a36=(a29*a31);
  a35=(a35+a36);
  a36=arg[1]? arg[1][4] : 0;
  a37=(a35*a36);
  a33=(a33-a37);
  a37=(a0*a33);
  a38=(a0*a35);
  a39=(a30+a36);
  a38=(a38*a39);
  a40=(a0*a32);
  a41=(a40*a30);
  a42=(a29*a5);
  a41=(a41-a42);
  a42=(a32*a31);
  a41=(a41+a42);
  a42=(a13*a41);
  a42=(a42*a35);
  a38=(a38-a42);
  a42=(a13*a35);
  a42=(a42*a41);
  a38=(a38+a42);
  a37=(a37+a38);
  a38=(a32*a34);
  a42=(a29*a25);
  a38=(a38+a42);
  a36=(a41*a36);
  a38=(a38+a36);
  a38=(a13*a38);
  a36=(a0*a39);
  a36=(a36*a39);
  a42=(a13*a39);
  a42=(a42*a41);
  a36=(a36+a42);
  a38=(a38-a36);
  a27=(a27*a38);
  a27=(a37+a27);
  a33=(a13*a33);
  a39=(a13*a39);
  a39=(a39*a35);
  a33=(a33+a39);
  a40=(a40*a33);
  a27=(a27+a40);
  a28=(a28+a27);
  a18=(a18+a28);
  a26=(a21*a26);
  a11=(a11*a20);
  a11=(a11*a20);
  a27=(a21*a20);
  a27=(a27*a23);
  a11=(a11+a27);
  a26=(a26-a11);
  a34=(a13*a34);
  a11=(a0*a30);
  a11=(a11*a30);
  a27=(a13*a30);
  a27=(a27*a31);
  a11=(a11+a27);
  a34=(a34-a11);
  a11=(a32*a38);
  a27=(a29*a33);
  a11=(a11-a27);
  a34=(a34+a11);
  a11=(a24*a34);
  a25=(a13*a25);
  a30=(a13*a30);
  a30=(a30*a5);
  a25=(a25+a30);
  a29=(a29*a38);
  a32=(a32*a33);
  a29=(a29+a32);
  a25=(a25+a29);
  a29=(a19*a25);
  a11=(a11-a29);
  a26=(a26+a11);
  a1=(a1*a26);
  a1=(a18+a1);
  a17=(a21*a17);
  a21=(a21*a20);
  a21=(a21*a2);
  a17=(a17+a21);
  a19=(a19*a34);
  a24=(a24*a25);
  a19=(a19+a24);
  a17=(a17+a19);
  a22=(a22*a17);
  a1=(a1+a22);
  a10=(a10+a1);
  a9=(a13*a9);
  a1=(a0*a12);
  a1=(a1*a12);
  a22=(a13*a12);
  a22=(a22*a7);
  a1=(a1+a22);
  a9=(a9-a1);
  a1=(a16*a26);
  a22=(a15*a17);
  a1=(a1-a22);
  a9=(a9+a1);
  a4=(a4*a9);
  a4=(a10+a4);
  a6=(a13*a6);
  a13=(a13*a12);
  a13=(a13*a8);
  a6=(a6+a13);
  a15=(a15*a26);
  a16=(a16*a17);
  a15=(a15+a16);
  a6=(a6+a15);
  a14=(a14*a6);
  a4=(a4+a14);
  a0=(a0*a3);
  a4=(a4-a0);
  if (res[0]!=0) res[0][0]=a4;
  if (res[0]!=0) res[0][1]=a10;
  if (res[0]!=0) res[0][2]=a18;
  if (res[0]!=0) res[0][3]=a28;
  if (res[0]!=0) res[0][4]=a37;
  return 0;
}

CASADI_SYMBOL_EXPORT int f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_f(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i, j;
  casadi_real w[58];
  casadi_int *iw = 0;
  const casadi_real* arg[2] = {0};
  casadi_real* res[1] = {0};
  if (argc>2) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f\" failed. Too many input arguments (%d, max 2)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+15);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+5, casadi_s0, w+15);
  --resc;
  res[0] = w+10;
  i = f(arg, res, iw, w+15, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s0, res[0]);
}
#endif

casadi_int main_f(casadi_int argc, char* argv[]) {
  casadi_int *iw = 0;
  casadi_real w[58];
  const casadi_real* arg[2] = {w+0, w+5};
  casadi_real* res[1] = {w+10};
  casadi_int j;
  casadi_real* a = w;
  for (j=0; j<10; ++j) scanf("%lg", a++);
  casadi_int flag = f(arg, res, iw, w+15, 0);
  if (flag) return flag;
  const casadi_real* r = w+10;
  for (j=0; j<5; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[2];
  int buf_ok = --argc >= 0 && !mxGetString(*argv++, buf, sizeof(buf));
  if (!buf_ok) {
    /* name error */
  } else if (strcmp(buf, "f")==0) {
    mex_f(resc, resv, argc, argv);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'f'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "f")==0) {
    return main_f(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'f'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
